services:
  nginx:
    build: ./nginx
    restart: always
    ports:
        - 80:80
    depends_on:
      - wp
      - pma

  wp:
    build: ./wp
    restart: always
    environment:
      - WORDPRESS_DB_HOST=ha
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_PASSWORD=wp
      - WORDPRESS_DB_NAME=wp
    depends_on:
      - ha
    volumes:
      - wp:/var/www/html

  pma:
    build: ./pma
    restart: always
    environment:
      - PMA_USER=pma
      - PMA_PASSWORD=pma
      - PMA_PMADB=pma
      - PMA_PORT=3306
      - PMA_HOST=ha
      - PMA_CONTROLUSER=root
      - PMA_CONTROLPASS=root
    depends_on:
      - ha

  db1:
    build: ./db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot -sBNe \"SHOW STATUS LIKE 'wsrep_cluster_size'\" | grep wsrep_cluster_size.*[1-3] || exit 0"]
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_REPLICATION_USER=replic
      - MARIADB_REPLICATION_PASSWORD=replic
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
    networks:
      - dbcluster
    volumes:
      - db1:/bitnami/mariadb:rw
      - ./db/setup_pma.sql:/docker-entrypoint-initdb.d/setup_pma.sql:ro
      - ./db/setup_wp.sql:/docker-entrypoint-initdb.d/setup_wp.sql:ro
      - ./db/setup_haproxy.sql:/docker-entrypoint-initdb.d/setup_haproxy.sql:ro

  db2:
    build: ./db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot -sBNe \"SHOW STATUS LIKE 'wsrep_cluster_size'\" | grep wsrep_cluster_size.*[1-3] || exit 1"]
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://db1:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_REPLICATION_USER=replic
      - MARIADB_REPLICATION_PASSWORD=replic
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db2:/bitnami/mariadb:rw
    depends_on:
      db1:
        condition: service_healthy
    networks:
      - dbcluster

  db3:
    build: ./db
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot -sBNe \"SHOW STATUS LIKE 'wsrep_cluster_size'\" | grep wsrep_cluster_size.*[1-3] || exit 1"]
    environment: 
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://db1:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_REPLICATION_USER=replic
      - MARIADB_REPLICATION_PASSWORD=replic
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db3:/bitnami/mariadb:rw
    depends_on:
      db1:
        condition: service_healthy
    networks:
      - dbcluster


  ha:
    build: ./ha
    networks:
      - dbcluster
      - default
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
      db3:
        condition: service_healthy
    volumes:
      - ./ha/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  dbcluster:


volumes:
  db1:
  db2:
  db3:
  wp:
